const $=s=>document.querySelector(s);
const state={tasks:[],view:'today',query:'',menuId:null,editId:null,deleteId:null,deleteReturnFocus:null,quickId:null,ready:false};
const localDate=s=>s?new Date(s):null;
const isToday=s=>{const d=localDate(s);return d&&d.toDateString()===new Date().toDateString()};
const isTomorrow=s=>{const d=localDate(s),x=new Date();x.setDate(x.getDate()+1);return d&&d.toDateString()===x.toDateString()};
const taskList=t=>t.list==='planned'?'planned':t.list==='today'?'today':t.due&&new Date(t.due).setHours(0,0,0,0)>new Date().setHours(0,0,0,0)?'planned':'today';
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=[['生活','#8eab86'],['工作','#ed8e82'],['学习','#a8a1d9'],['健康','#9abbd8'],['家庭','#c9a17d'],['家务','#b8ad87'],['社交','#e6a2ad'],['财务','#d8b56d'],['购物','#e5a888'],['出行','#86b2aa'],['旅行','#82b8b6'],['运动','#8caeb7'],['饮食','#dba98b'],['兴趣','#b4a5cf'],['创作','#ca9fbb'],['娱乐','#d5a9bc'],['宠物','#a6b893'],['其他','#b7a899']];
const categoryColor=name=>categories.find(x=>x[0]===name)?.[1]||'#b7a899';
function send(type,extra={}){if(window.chrome?.webview)chrome.webview.postMessage({type,...extra})}
function save(){send('save',{tasks:state.tasks})}
function formatDue(s){if(!s)return '';const d=localDate(s);if(!d||Number.isNaN(+d))return '';const day=isToday(s)?'今天':isTomorrow(s)?'明天':(d.getMonth()+1)+'/'+d.getDate();return day+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function shown(){let xs=state.tasks.filter(t=>state.view==='done'?t.completed:state.view==='all'?true:!t.completed&&taskList(t)===state.view);if(state.query){const q=state.query.toLowerCase();xs=xs.filter(t=>t.title.toLowerCase().includes(q)||(t.category||'').toLowerCase().includes(q))}return xs.sort((a,b)=>Number(a.completed)-Number(b.completed)||(a.due||'9999').localeCompare(b.due||'9999')||(a.created||'').localeCompare(b.created||''))}
function taskMarkup(t){const priority=['普通','重要','紧急'].includes(t.priority)?t.priority:'普通';const over=t.due&&!t.completed&&new Date(t.due)<new Date(),dueText=formatDue(t.due);return '<div class="task '+(t.completed?'done':'')+'" data-id="'+safe(t.id)+'"><input class="check" type="checkbox" '+(t.completed?'checked':'')+' aria-label="完成 '+safe(t.title)+'"><div class="task-title" title="点击编辑">'+safe(t.title)+'</div><div class="tag"><span class="category-inline" role="button" tabindex="0" title="点击修改分类" aria-label="修改 '+safe(t.title)+' 的分类"><i class="tag-dot" style="background:'+categoryColor(t.category)+'"></i><span class="category-name">'+safe(t.category||'生活')+'</span></span><span class="priority-inline priority-'+(priority==='紧急'?'urgent':priority==='重要'?'important':'normal')+'" role="button" tabindex="0" title="点击修改优先级" aria-label="修改 '+safe(t.title)+' 的优先级">· '+priority+'</span></div><div class="due '+(over?'overdue':'')+' '+(dueText?'':'no-due')+'" role="button" tabindex="0" title="点击修改时间" aria-label="修改 '+safe(t.title)+' 的时间">'+safe(dueText||'＋ 时间')+'</div><button class="more" title="更多">⋯</button></div>'}
function completedGroup(list,label,items){return '<section class="completed-group" data-list="'+list+'"><h3 class="completed-group-title"><span>'+label+'</span><span class="completed-group-count">'+items.length+' 件</span></h3>'+(items.length?items.map(taskMarkup).join(''):'<div class="completed-group-empty">这一组还没有完成的小事 ♡</div>')+'</section>'}
function closeCategoryMenus(){document.querySelectorAll('.category-picker').forEach(p=>{p.querySelector('.category-menu').classList.add('hidden');p.querySelector('input').setAttribute('aria-expanded','false')})}
function openCategoryMenu(picker,query=''){closeCategoryMenus();const input=picker.querySelector('input'),menu=picker.querySelector('.category-menu');const choices=categories.filter(x=>x[0].includes(query));menu.innerHTML='<div class="category-menu-title">选一个适合的小分类</div><div class="category-grid">'+choices.map(([name,color])=>'<button type="button" class="category-choice '+(input.value===name?'selected':'')+'" role="option" aria-selected="'+(input.value===name)+'" data-value="'+safe(name)+'"><i class="category-dot" style="background:'+color+'"></i>'+safe(name)+'</button>').join('')+'</div><div class="category-menu-tip">'+(choices.length?'也可以直接输入自定义分类':'没有匹配项，可直接输入自定义分类')+'</div>';menu.classList.remove('hidden');input.setAttribute('aria-expanded','true')}
document.querySelectorAll('.category-picker').forEach(picker=>{const input=picker.querySelector('input'),menu=picker.querySelector('.category-menu');input.addEventListener('focus',()=>openCategoryMenu(picker));input.addEventListener('input',()=>openCategoryMenu(picker,input.value.trim()));picker.querySelector('.category-toggle').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();menu.classList.contains('hidden')?openCategoryMenu(picker):closeCategoryMenus()});menu.addEventListener('click',e=>{const option=e.target.closest('.category-choice');if(!option)return;e.preventDefault();e.stopPropagation();input.value=option.dataset.value;closeCategoryMenus()})});
document.addEventListener('click',e=>{if(!e.target.closest('.category-picker'))closeCategoryMenus()});
function closeQuickPanels(){state.quickId=null;$('#quickCategory').classList.add('hidden');$('#quickPriority').classList.add('hidden');$('#quickDue').classList.add('hidden')}
function placeQuick(panel,anchor){panel.classList.remove('hidden');const scene=$('.scene').getBoundingClientRect(),r=anchor.getBoundingClientRect();let x=Math.max(12,Math.min(r.left-scene.left,scene.width-panel.offsetWidth-12)),y=r.bottom-scene.top+8;if(y+panel.offsetHeight>scene.height-12)y=r.top-scene.top-panel.offsetHeight-8;panel.style.left=x+'px';panel.style.top=Math.max(12,y)+'px'}
function renderQuickCategories(query=''){const current=state.tasks.find(t=>t.id===state.quickId)?.category||'',choices=categories.filter(([name])=>name.includes(query));$('#quickCategoryChoices').innerHTML=choices.map(([name,color])=>'<button type="button" class="category-choice '+(current===name?'selected':'')+'" data-value="'+safe(name)+'"><i class="category-dot" style="background:'+color+'"></i>'+safe(name)+'</button>').join('')||'<span class="quick-no-match">没有匹配项，可保存自定义分类</span>'}
function openQuickCategory(t,anchor){closeCategoryMenus();closeQuickPanels();state.quickId=t.id;$('#quickCategoryInput').value='';renderQuickCategories();placeQuick($('#quickCategory'),anchor);$('#quickCategoryInput').focus()}
function openQuickPriority(t,anchor){closeCategoryMenus();closeQuickPanels();state.quickId=t.id;$('#quickPriority').querySelectorAll('[data-value]').forEach(b=>b.classList.toggle('selected',b.dataset.value===(t.priority||'普通')));placeQuick($('#quickPriority'),anchor);$('#quickPriority .selected').focus()}
function openQuickDue(t,anchor){closeCategoryMenus();closeQuickPanels();state.quickId=t.id;$('#quickDueInput').value=t.due||'';placeQuick($('#quickDue'),anchor);$('#quickDueInput').focus()}
function saveQuickCategory(value){const t=state.tasks.find(x=>x.id===state.quickId);if(!t||!value.trim())return;t.category=value.trim();closeQuickPanels();save();render()}
function saveQuickPriority(value){const t=state.tasks.find(x=>x.id===state.quickId);if(!t||!['普通','重要','紧急'].includes(value))return;t.priority=value;closeQuickPanels();save();render()}
function saveQuickDue(value){const t=state.tasks.find(x=>x.id===state.quickId);if(!t)return;t.due=value;t.reminded=false;closeQuickPanels();save();render()}
$('#quickCategoryInput').addEventListener('input',e=>renderQuickCategories(e.target.value.trim()));
$('#quickCategoryInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveQuickCategory(e.target.value)}});
$('#quickCategoryChoices').addEventListener('click',e=>{const option=e.target.closest('.category-choice');if(option)saveQuickCategory(option.dataset.value)});
$('#quickCategorySave').addEventListener('click',()=>saveQuickCategory($('#quickCategoryInput').value));
$('#quickPriority').addEventListener('click',e=>{const option=e.target.closest('[data-value]');if(option)saveQuickPriority(option.dataset.value)});
$('#quickDueSave').addEventListener('click',()=>saveQuickDue($('#quickDueInput').value));
$('#quickDueClear').addEventListener('click',()=>saveQuickDue(''));
$('#quickDueInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveQuickDue(e.target.value)}});
function render(){document.body.dataset.view=state.view;const headings={today:'今日的小事',planned:'计划的小事',all:'全部的小事',done:'完成的小事'};$('#heading').innerHTML=safe(headings[state.view])+' <span class="heart">♡</span>';$('#listHeading').textContent={today:'今天，慢慢完成',planned:'接下来的安排',all:'每件小事都值得',done:'做得很好呀'}[state.view];$('#dateLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',weekday:'short'}).format(new Date());document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const xs=shown();$('#count').textContent=xs.length?xs.length+' 件小事':'';$('#empty').textContent={today:'这里还没有小事，写下第一件吧 ♡',planned:'还没有计划中的小事，写下一件吧 ♡',all:'这里还没有小事，写下第一件吧 ♡',done:'还没有完成的小事，慢慢来 ♡'}[state.view];
 $('#tasks').innerHTML=state.view==='done'&&xs.length?completedGroup('today','今日任务 · 已完成',xs.filter(t=>taskList(t)==='today'))+completedGroup('planned','计划任务 · 已完成',xs.filter(t=>taskList(t)==='planned')):xs.map(taskMarkup).join('');$('#empty').classList.toggle('hidden',xs.length>0)}
function add(){const box=$('#newTitle'),title=box.value.trim();if(!title){box.focus();return}state.tasks.push({id:crypto.randomUUID(),title,list:$('#newList').value,category:$('#newCategory').value.trim()||'生活',priority:$('#newPriority').value,due:$('#newDue').value||'',completed:false,reminded:false,created:new Date().toISOString()});box.value='';$('#newDue').value='';closeCategoryMenus();save();render();box.focus()}
function openEdit(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;closeQuickPanels();state.editId=id;$('#editTitle').value=t.title;$('#editList').value=taskList(t);$('#editDue').value=t.due||'';$('#editCategory').value=t.category||'生活';$('#editPriority').value=t.priority||'普通';$('#modal').classList.remove('hidden');$('#editTitle').focus()}
function closeEdit(){state.editId=null;closeCategoryMenus();$('#modal').classList.add('hidden')}
function deleteTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;closeQuickPanels();state.deleteId=id;state.deleteReturnFocus=document.activeElement;$('#deleteTitle').textContent='“'+t.title+'”';$('#deleteModal').classList.remove('hidden');$('#cancelDelete').focus()}
function closeDelete(){state.deleteId=null;$('#deleteModal').classList.add('hidden');if(state.deleteReturnFocus?.isConnected)state.deleteReturnFocus.focus();state.deleteReturnFocus=null}
function confirmDelete(){const id=state.deleteId;if(!id)return;closeDelete();state.tasks=state.tasks.filter(x=>x.id!==id);save();render()}
window.receiveState=function(tasks){state.tasks=Array.isArray(tasks)?tasks.map(t=>({...t,list:taskList(t)})):[];state.ready=true;render()};
window.onReminder=function(id){const t=state.tasks.find(x=>x.id===id);if(t)t.reminded=true};
document.addEventListener('click',e=>{if(!e.target.closest('#menu'))$('#menu').classList.add('hidden');if(!e.target.closest('.quick-popover,.task .category-inline,.task .priority-inline,.task .due'))closeQuickPanels();const row=e.target.closest('.task');if(!row)return;const t=state.tasks.find(x=>x.id===row.dataset.id);if(!t)return;if(e.target.matches('.check')){t.completed=e.target.checked;save();render()}else if(e.target.closest('.more')){const m=$('#menu'),r=e.target.getBoundingClientRect();state.menuId=t.id;m.style.left=Math.min(r.left-80,innerWidth-160)+'px';m.style.top=Math.min(r.bottom+2,innerHeight-95)+'px';m.classList.remove('hidden')}else if(e.target.closest('.category-inline'))openQuickCategory(t,e.target.closest('.category-inline'));else if(e.target.closest('.priority-inline'))openQuickPriority(t,e.target.closest('.priority-inline'));else if(e.target.closest('.due'))openQuickDue(t,e.target.closest('.due'));else if(e.target.closest('.task-title'))openEdit(t.id)});
$('#menu').addEventListener('click',e=>{const action=e.target.dataset.action,id=state.menuId;$('#menu').classList.add('hidden');if(action==='edit')openEdit(id);if(action==='delete')deleteTask(id)});
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{closeQuickPanels();state.view=b.dataset.view;$('#newList').value=state.view==='planned'?'planned':'today';render()}));
$('#addBtn').addEventListener('click',add);$('#newTitle').addEventListener('keydown',e=>{if(e.key==='Enter')add()});
$('#optionsToggle').addEventListener('click',()=>$('#options').classList.toggle('hidden'));
$('#searchToggle').addEventListener('click',()=>{$('#searchWrap').classList.toggle('open');if($('#searchWrap').classList.contains('open'))$('#search').focus();else{$('#search').value='';state.query='';render()}});
$('#search').addEventListener('input',e=>{state.query=e.target.value.trim();render()});
$('#modalClose').addEventListener('click',closeEdit);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeEdit()});
$('#cancelDelete').addEventListener('click',closeDelete);$('#confirmDelete').addEventListener('click',confirmDelete);$('#deleteModal').addEventListener('click',e=>{if(e.target.id==='deleteModal')closeDelete()});
$('#saveEdit').addEventListener('click',()=>{const t=state.tasks.find(x=>x.id===state.editId),title=$('#editTitle').value.trim();if(!t||!title)return;t.title=title;t.list=$('#editList').value;t.due=$('#editDue').value||'';t.category=$('#editCategory').value.trim()||'生活';t.priority=$('#editPriority').value;t.reminded=false;save();closeEdit();render()});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.task .category-inline,.task .priority-inline,.task .due')){e.preventDefault();e.target.click();return}if(e.key==='Escape'){if(!$('#quickCategory').classList.contains('hidden')||!$('#quickPriority').classList.contains('hidden')||!$('#quickDue').classList.contains('hidden')){closeQuickPanels();return}if(document.querySelector('.category-menu:not(.hidden)')){closeCategoryMenus();return}if(!$('#deleteModal').classList.contains('hidden'))closeDelete();else closeEdit();$('#menu').classList.add('hidden')}if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchWrap').classList.add('open');$('#search').focus()}});
$('#windowBar').addEventListener('mousedown',e=>{if(e.target.closest('.window-controls'))return;send('window',{action:'drag'})});
$('#windowBar').addEventListener('dblclick',e=>{if(e.target.closest('.window-controls'))return;send('window',{action:'maximize'})});
$('#minimizeBtn').addEventListener('click',()=>send('window',{action:'minimize'}));
$('#maximizeBtn').addEventListener('click',()=>send('window',{action:'maximize'}));
$('#closeBtn').addEventListener('click',()=>send('window',{action:'close'}));
if(window.chrome?.webview){chrome.webview.addEventListener('message',e=>{if(e.data?.type==='state')window.receiveState(e.data.tasks);if(e.data?.type==='reminded')window.onReminder(e.data.id)});send('ready')}else{window.receiveState([])}
